### ISSUE TITLE
ChangeFeed Improvements

### ISSUE THREAD

**Issue by arunoda** [cloudant/meteor-couchdb#5]
First of all: awesome work guys.

In Meteor 1.2 (currently on devel branch) there are some massive CPU related improvements has been added to oplog related logic. 

It's seems like you guys using the same logic as MongoDB Oplog Tailing.
So, it's a good idea to add the changes added here: https://github.com/meteor/meteor/pull/4694

May be you guys need to wait until Meteor 1.2 ships because this needs some improvements to the `writefence` package. May be we can do something about it.

**Comment by mariobriggs** [comment]
@arunoda first thanks for the kudos.

Quickly glanced through the PR  link you listed above and i will dig in deeper in some time.

 However at quick glance : our waitUntilCaughtup had to be different since CouchDB's sequence #'s are opaque strings rather than timestamps (so one cannot do >= comparsions). So we don't fetch the current sequence # from the server, but instead use the returned _rev & _id from the CouchDB response to the update to track which change we are looking for from the _changes feed to have reached us.

Yeah i did notice in my testing that the waitUntilCaughtup gets fired for each client subscribed/connected, something i didnt realize first and hence had to make some additions to above to handle this. So will cross-check in more detail with the and confirm whether we  need that or not.

**Comment by mariobriggs** [comment]
ah since there is now a 'fence.onBeforeFire()' , we should implement it for sure with 1.2 (and i can remove the additional client side timestamp i added over and above the _id & _rev to handle it being fired for each subscribed client) . What thoughts u had for prior to 1.2?

**Comment by mariobriggs** [comment]
now supports onBeforeFire() via commit 7772eab21151e5cd4994ea37a64c434d88e8bf4a
